#!/usr/bin/env python3
"""Emit View/LanguageFlags.qml from one table.

Single source of truth for the UI-language -> (display name, flag codes) map.
Run when the table changes; the generated singleton is consumed by
SettingsPage's interface-language picker. Keep _TENJIN_FLAG_CODES in
cmake/Assets.cmake in sync with the flag codes used here.

Flag codes are ISO-3166-1 alpha-2 (lipis/flag-icons file names). Languages with
no single unambiguous flag use multiple; choices follow common CLDR/industry
practice and can be edited here in one place.
"""
from __future__ import annotations

from pathlib import Path

# code: (english_name, [iso3166-1 alpha-2 flag codes])
TABLE: dict[str, tuple[str, list[str]]] = {
    "en":    ("English",       ["gb", "us"]),
    "ja":    ("\u65E5\u672C\u8A9E", ["jp"]),
    "es":    ("Espa\u00F1ol",   ["es", "mx"]),
    "fr":    ("Fran\u00E7ais",  ["fr"]),
    "de":    ("Deutsch",        ["de"]),
    "it":    ("Italiano",       ["it"]),
    "pt":    ("Portugu\u00EAs", ["pt", "br"]),
    "ru":    ("\u0420\u0443\u0441\u0441\u043A\u0438\u0439", ["ru"]),
    "ko":    ("\uD55C\uAD6D\uC5B4", ["kr"]),
    "zh_CN": ("\u4E2D\u6587 (\u7B80\u4F53)", ["cn"]),
    "zh_TW": ("\u4E2D\u6587 (\u7E41\u9AD4)", ["tw"]),
    "ar":    ("\u0627\u0644\u0639\u0631\u0628\u064A\u0629", ["sa"]),
}


def _q(s: str) -> str:
    """Quote a string for QML as a \\uXXXX-escaped JS string literal."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif 0x20 <= o < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{o:04x}")
    return '"' + "".join(out) + '"'


def render() -> str:
    rows = []
    for code, (name, flags) in TABLE.items():
        arr = ", ".join(_q(f) for f in flags)
        rows.append(
            f"        {_q(code)}: {{ "
            f'"name": {_q(name)}, "flags": [{arr}] }}'
        )
    body = ",\n".join(rows)
    return (
        "pragma Singleton\n"
        "import QtQuick\n\n"
        "// GENERATED by tools/scripts/gen_lang_flags.py — DO NOT EDIT.\n"
        "// Edit the TABLE in that script and re-run, then keep the flag codes\n"
        "// in cmake/Assets.cmake in sync.\n"
        "QtObject {\n"
        "    readonly property var map: {\n"
        f"{body}\n"
        "    }\n\n"
        "    // ISO-3166 alpha-2 flag codes for a language, or [] if unmapped.\n"
        "    function flags(code) { return map[code] ? map[code].flags : [] }\n\n"
        "    // Native display name for a language, or the code if unmapped.\n"
        "    function name(code) { return map[code] ? map[code].name : code }\n"
        "}\n"
    )


def main() -> None:
    out = Path(__file__).resolve().parents[2] / "View" / "LanguageFlags.qml"
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
