# Miniz.cmake — miniz ZIP library as a clean, self-contained CMake target.
#
# miniz is an MIT-licensed, dependency-free ZIP/deflate library used for Anki
# .apkg import. This module fetches the source and builds a proper `miniz`
# static target with full usage requirements (include dirs, compile
# definitions) so consumers just `target_link_libraries(... PRIVATE miniz)`
# and CMake handles transitive include paths and link ordering automatically.
#
# Why we build it ourselves rather than add_subdirectory(miniz):
#   * miniz's bundled CMakeLists declares its own C `project()`, which under
#     cross-compilation re-runs compiler detection and previously fell back to
#     the host compiler, breaking the configure step.
#   * It also targets cmake_minimum_required < 3.5, emitting a deprecation
#     warning, and builds shared libs / examples we do not want.
# Compiling the sources directly with the parent project's toolchain avoids all
# of that while still producing a first-class target.

include_guard(GLOBAL)
include(FetchContent)

FetchContent_Declare(miniz
    GIT_REPOSITORY https://github.com/richgel999/miniz.git
    GIT_TAG        3.0.2
    GIT_SHALLOW    TRUE
    # SOURCE_SUBDIR points at a non-existent dir so MakeAvailable downloads and
    # populates the source WITHOUT configuring miniz's own CMakeLists.
    SOURCE_SUBDIR  _tenjin_no_cmake
)
FetchContent_MakeAvailable(miniz)

# miniz 3.x splits its implementation across several translation units. The
# archive API (mz_zip_*) lives in miniz_zip.c, deflate in miniz_tdef.c, and
# inflate in miniz_tinfl.c. Compiling only miniz.c leaves those undefined at
# link time, so we compile every source that exists. Older release tarballs
# ship a single amalgamated source under amalgamation/ instead — handle both.
set(_miniz_srcs "")
foreach(_f IN ITEMS miniz.c miniz_tdef.c miniz_tinfl.c miniz_zip.c)
    if(EXISTS "${miniz_SOURCE_DIR}/${_f}")
        list(APPEND _miniz_srcs "${miniz_SOURCE_DIR}/${_f}")
    endif()
endforeach()
if(NOT _miniz_srcs AND EXISTS "${miniz_SOURCE_DIR}/amalgamation/miniz.c")
    list(APPEND _miniz_srcs "${miniz_SOURCE_DIR}/amalgamation/miniz.c")
    set(_miniz_inc "${miniz_SOURCE_DIR}/amalgamation")
else()
    set(_miniz_inc "${miniz_SOURCE_DIR}")
endif()
if(NOT _miniz_srcs)
    message(FATAL_ERROR
        "miniz: no source files found under ${miniz_SOURCE_DIR}. "
        "The fetch may have failed or the upstream layout changed.")
endif()

# miniz.h includes "miniz_export.h", a visibility header that miniz's own CMake
# normally generates via generate_export_header(). Since we bypass that, we
# generate the static-build equivalent (every export macro empty) and define
# MINIZ_STATIC_DEFINE so any guarded code takes the static branch.
set(_miniz_gen "${CMAKE_BINARY_DIR}/generated/miniz")
file(MAKE_DIRECTORY "${_miniz_gen}")
file(WRITE "${_miniz_gen}/miniz_export.h"
"#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H
/* Generated by Tenjin (cmake/Miniz.cmake) for a static miniz build. */
#define MINIZ_EXPORT
#define MINIZ_NO_EXPORT
#define MINIZ_DEPRECATED
#define MINIZ_DEPRECATED_EXPORT
#define MINIZ_DEPRECATED_NO_EXPORT
#endif /* MINIZ_EXPORT_H */
")

add_library(miniz STATIC ${_miniz_srcs})
add_library(miniz::miniz ALIAS miniz)

target_compile_definitions(miniz PUBLIC MINIZ_STATIC_DEFINE)
target_include_directories(miniz PUBLIC
    "${_miniz_gen}"   # generated miniz_export.h (must precede the source dir)
    "${_miniz_inc}")
set_target_properties(miniz PROPERTIES
    C_STANDARD 11
    POSITION_INDEPENDENT_CODE ON)
