pragma Singleton
import QtQuick

// GENERATED by tools/scripts/gen_lang_flags.py — DO NOT EDIT.
// Edit the TABLE in that script and re-run, then keep the flag codes
// in cmake/Assets.cmake in sync.
QtObject {
    readonly property var map: {
        "en": { "name": "English", "flags": ["gb", "us"] },
        "ja": { "name": "\u65e5\u672c\u8a9e", "flags": ["jp"] },
        "es": { "name": "Espa\u00f1ol", "flags": ["es", "mx"] },
        "fr": { "name": "Fran\u00e7ais", "flags": ["fr"] },
        "de": { "name": "Deutsch", "flags": ["de"] },
        "it": { "name": "Italiano", "flags": ["it"] },
        "pt": { "name": "Portugu\u00eas", "flags": ["pt", "br"] },
        "ru": { "name": "\u0420\u0443\u0441\u0441\u043a\u0438\u0439", "flags": ["ru"] },
        "ko": { "name": "\ud55c\uad6d\uc5b4", "flags": ["kr"] },
        "zh_CN": { "name": "\u4e2d\u6587 (\u7b80\u4f53)", "flags": ["cn"] },
        "zh_TW": { "name": "\u4e2d\u6587 (\u7e41\u9ad4)", "flags": ["tw"] },
        "ar": { "name": "\u0627\u0644\u0639\u0631\u0628\u064a\u0629", "flags": ["sa"] }
    }

    // ISO-3166 alpha-2 flag codes for a language, or [] if unmapped.
    function flags(code) { return map[code] ? map[code].flags : [] }

    // Native display name for a language, or the code if unmapped.
    function name(code) { return map[code] ? map[code].name : code }
}
